### ISSUE TITLE
Wifi and Photos Map issues

### ISSUE THREAD

**Issue by iosdeveloper** [nst/SpyPhone#2]
On iOS 4.3.2, iPhone 4 SpyPhone crashes when clicking Photos Map button.
Wifi Map shows ocean and no pins even if list contains networks.

**Comment by nst** [comment]
The crash is fixed. The mapping service for BSSID -> GPS coordinates is down, I will update SpyPhone when I find a service that works.

**Comment by iosdeveloper** [comment]
Alright, checked out the latest version. Photos Map does no longer crash, however it does not work at all. It displays a pin in the Atlantic Ocean of photos I have taken in Germany. This issue must be reopen (I do not have permission to do so).

**Comment by nst** [comment]
Photos are not available anymore, and so no geotag is available. I should probably remove this tab from SpyPhone.
